### ISSUE TITLE
Please Add .BUP File Support

### ISSUE THREAD

**Issue by slinga-homebrew** [hitomi2500/ss-save-parser#1]
Please add .BUP file support as documented here: https://github.com/slinga-homebrew/Save-Game-BUP-Scripts. The .BUP file format is being used by Psuedo Saturn Kai and will soon be added to Save Game Copier and Save Game Extractor. Thanks in advance.

**Comment by hitomi2500** [comment]
.BUP support It is done (both insert and extract), but i don't have the time to test it now. If someone can spare some time for testing, i can build a beta.

**Comment by slinga-homebrew** [comment]
Thanks, I'll try to build on Linux.

**Comment by slinga-homebrew** [comment]
I tested with 0.9.7 with Wine. I loaded the .BKR (https://github.com/slinga-homebrew/Save-Game-Copier/issues/37#issuecomment-792325272) successfully and can see two save files. However I was unable to export to .BUP file. When I click on extract it opens a "Load Savegame" dialog. I would expect it to say "Export Savegame".

Can you please advise? Thanks.

**Comment by hitomi2500** [comment]
This bug is fixed in 0.9.8. Thanks for reporting.

**Comment by slinga-homebrew** [comment]
Thanks, it looks like it's working.
