### ISSUE TITLE
[BUG] When extracting n save files, n-1 files get extracted and the nth file is missing.

### ISSUE THREAD

**Issue by privateye** [hitomi2500/ss-save-parser#2]
As described in the title. This bug occurs in ss-save-parser v0.9.8.

As an example, here I have selected 10 save files:
![1](https://user-images.githubusercontent.com/69020283/113457976-359c8a00-9409-11eb-9777-1ba47bcb2d1f.png)

Once extracted, only 9 files get written to the destination directory and the 10th save file (`HOLY_ARK_01`) is missing.
![2](https://user-images.githubusercontent.com/69020283/113458326-e014ad00-9409-11eb-96d1-3d441eee4c6b.png)

**Comment by hitomi2500** [comment]
Bug confirmed on my side, will fix if soon.

**Comment by hitomi2500** [comment]
Totally forgout about this bug, sorry. It's fixed now, but the machine with deployment settings is unavailable currently, i will try to make a release tomorrow.

**Comment by privateye** [comment]
Thanks. Once you release the next version and I confirm that the bug is fixed, I'll go ahead and close this issue.

**Comment by hitomi2500** [comment]
0.9.9 released.

**Comment by privateye** [comment]
Bug fixed.
